[![Build](https://github.com/l3aalteshuva/nightwatch-typescript-boilerplate/actions/workflows/build.yml/badge.svg?branch=l3aalteshuva-patch-1)](https://github.com/l3aalteshuva/nightwatch-typescript-boilerplate/actions/workflows/build.yml)
